# Usign the Clean Blog theme

title: The CogML Seminar
author: cogml-seminar
email: rachid.riad@inria.fr
description: When Cognitive Sciences Meet Artificial Intelligence
baseurl: ""
url: "https://cogml-seminar.github.io/"
github_username: cogml-seminar

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: The COGAI Seminar
gems:
  - jekyll-feed
  - jekyll-paginate
